# Generated by Django 6.0.2 on 2026-02-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('amount', models.PositiveIntegerField()),
                ('shop_id', models.CharField(max_length=127)),
            ],
        ),
    ]
