# Generated by Django 6.0.2 on 2026-02-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=127)),
                ('address', models.TextField()),
                ('payment', models.CharField(choices=[('Pix', 'Pix'), ('Cartão', 'Cartão'), ('Boleto', 'Boleto')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
